# Generated by Django 5.2.10 on 2026-02-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
    ]
