# Generated by Django 5.2.10 on 2026-02-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_available',
            field=models.IntegerField(default=0),
        ),
    ]
